import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: {
    template: "%s | Shopps",
    default: "Shopps"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body suppressHydrationWarning
        className={`antialiased ${inter.variable} font-sans text-slate-800 selection:bg-orange-200`}
      >
        <Toaster position="top-center"/>
        {children}
      </body>
    </html>
  );
}
